// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj8Nf-s_dn4n6svx0LupE4vithnasn5J0',
    appId: '1:570682926827:web:a61dd391ab2887fec380ae',
    messagingSenderId: '570682926827',
    projectId: 'we-chat-91b3c',
    authDomain: 'we-chat-91b3c.firebaseapp.com',
    storageBucket: 'we-chat-91b3c.appspot.com',
    measurementId: 'G-JJQCETQZ00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7OH7I-FdDHyW1d0ZCaMZuXygiaSTGyzg',
    appId: '1:570682926827:android:798d4303e4e2bb96c380ae',
    messagingSenderId: '570682926827',
    projectId: 'we-chat-91b3c',
    storageBucket: 'we-chat-91b3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMDvdiCGkM55DUTzRg3IF_Q3rDtTKcV6g',
    appId: '1:570682926827:ios:46ae59be6d6c3e61c380ae',
    messagingSenderId: '570682926827',
    projectId: 'we-chat-91b3c',
    storageBucket: 'we-chat-91b3c.appspot.com',
    androidClientId: '570682926827-6ug6j7u6j5fk65cvh1pfhkdr0b14ki07.apps.googleusercontent.com',
    iosClientId: '570682926827-n3p9i8j1745vjqsrrof6arctrtgp4gjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

}